"""empty message

Revision ID: 704b3d3a2764
Revises: 47c7b7cfd432
Create Date: 2025-04-30 18:39:40.619900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704b3d3a2764'
down_revision = '47c7b7cfd432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_people')
    op.drop_table('user_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_planet',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='user_planet_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_planet_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id', name='user_planet_pkey')
    )
    op.create_table('user_people',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='user_people_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'people_id', name='user_people_pkey')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
